CREATE TABLE IF NOT EXISTS `board` (
  `num` int(11) NOT NULL AUTO_INCREMENT,
  `parent` int(11) DEFAULT NULL,
  `timestamp` int(11) DEFAULT NULL,
  `lasthit` int(11) DEFAULT NULL,
  `ip` text,
  `name` text,
  `trip` text,
  `email` text,
  `subject` text,
  `password` text,
  `comment` text,
  `image` text,
  `size` int(11) DEFAULT NULL,
  `md5` text,
  `width` int(11) DEFAULT NULL,
  `height` int(11) DEFAULT NULL,
  `thumbnail` text,
  `tn_width` text,
  `tn_height` text,
  `autosage` tinyint(1) DEFAULT NULL,
  `adminpost` tinyint(1) DEFAULT NULL,
  `uploadname` text,
  `displaysize` text,
  `locked` tinyint(1) DEFAULT NULL,
  `sticky` tinyint(1) DEFAULT NULL,
  `imageid_1` bigint(20) DEFAULT NULL,
  `imageid_2` bigint(20) DEFAULT NULL,
  `imageid_3` bigint(20) DEFAULT NULL,
  `location` varchar(25) DEFAULT 'UNKNOWN',
  `ssl` text,
  PRIMARY KEY (`num`),
  KEY `imageid_1` (`imageid_1`),
  KEY `imageid_2` (`imageid_2`),
  KEY `imageid_3` (`imageid_3`),
  FULLTEXT KEY `uploadname` (`uploadname`),
  FULLTEXT KEY `image` (`image`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;